### PR TITLE
Creating a proposer client interface

### PR DESCRIPTION
**Pull request by nisdas**
Addresses #59 

- [x] Create a basic interface so that when `geth sharding-proposer ` is entered a basic proposer rpc - client is initiated

### CODE REVIEW

**Comment by prestonvanloon** [comment]
Could you add a pull request description? What are the changes you are making here?

**Comment by nisdas** [comment]
Added a description above

**Comment by terenc3t** [comment]
Should we add tests and avoid the duplicate code within clients?

**Comment by rauljordan** [comment]
I think we should call it shardingClient so that we're different that the ethclient or other packages in the repo.

**Comment by terenc3t** [comment]
I really like this initiative to address our client side abstraction. +1 to shardingClient

**Comment by rauljordan** [comment]
So the common methods can be receivers for shardingClient, while specific ones can be receivers of CollatorClient and ProposerClient.

**Comment by nisdas** [comment]
Hey guys, I will be putting up a design proposal soon for refactoring/abstraction of our code so as to provide a solution for the issues that have been raised

**Pull request closed without merging**
