### PR TITLE
WIP: Proposal Pool Code Implementation

### PR DESCRIPTION
**Pull request by terenc3t**
### TODOs:
- [ ] implement _proposal_list_ for sorting collation per proposer
- [ ] implement _proposal_pool_ for containing all the current known collations
- [ ] implement _tests_

Please check out #63 for proposal pool's design spec and discussion in detail

### CODE REVIEW

**Comment by terenc3t** [comment]
This is currently blocked by #72 
We'll need to figure out the protocol to use first before proceeding with this

**Comment by terenc3t** [comment]
@prestonvanloon that should be proposal pool, not collation pool, will fix that now

**Comment by enriquefynn** [comment]
This is almost a copy of tx_list.go, isn't there a way to reuse that code?!

**Comment by terenc3t** [comment]
The `collation_list.go` works with collation number and proposer bid since collation fields are completely different than tx fields, any idea on how to reuse `tx_list.go` w/o modifying on top? not sure if that's possible

**Comment by prestonvanloon** [comment]
Can you add some details on your design considerations? 

For example, why do we want to know if the proposal is the cheapest? 
What considers a collation proposal to be ready? Is it when the collation body has been published?

**Comment by terenc3t** [comment]
We are using a heap interface over collations to sort collations based on bid price and to discard cheapest collation when proposal pool fills up
Collation proposal is ready after the body has been published

**Comment by prestonvanloon** [comment]
So that is only used for insertion? Why is it a public method rather than an internal part of `Put`? 

Please add your full design considerations to the pull request body for context and historical record.

**Comment by terenc3t** [comment]
I wasn't sure if everything is still going to be under Sharding package or we are going to separate them into Collator and Proposer packages. Will add full design considerations to the PR later

**Comment by rauljordan** [comment]
Not needed for phase 1...closing for now.

**Pull request closed without merging**
