### PR TITLE
Refactoring of Code

### PR DESCRIPTION
**Pull request by nisdas**
It was agreed by the team in #60 to refactor the code in order to prevent duplication of code and for easier testing. 
The objectives of this PR are to 
- [ ] Abstract all common methods into a common interface which would be in the sub-package `sharding/client`
- [ ] Add the collator and proposer specific methods in `sharding/collator` and `sharding/proposer` respectively.
- [ ] Write tests for the general client, to ensure that it is running correctly 

More documentation can be found here : 
https://docs.google.com/document/d/1__74pTWFpzfLLJ8017XeWQWJfs89YgTGxuefjkFUAaY/edit

### CODE REVIEW

**Comment by rauljordan** [comment]
Not a big fan of creating individual packages, especially as this will be really difficult for upstream merging. Just created #83 as an alternative proposal to this problem.

**Comment by prestonvanloon** [comment]
@rauljordan Individual packages under the sharding package make no difference on the ease or difficulty of merging upstream.

**Comment by terenc3t** [comment]
I agree there's no difference, the question is do we need it. When we introduce more actors (ex: executor), are we going to create a executor package as well?

**Comment by prestonvanloon** [comment]
@terenc3t Yes, we need packages for proper code organization. As the sharding features grow, it will be unmaintainable to have a single package that does everything.

Absolutely, the execution would go in another package since it’s another responsibility.

**Comment by rauljordan** [comment]
Referenced by #85 and it includes @nisdas's work. We can close this one.

**Pull request closed without merging**
