### PR TITLE
Change Actor Name Notary to Attester

### LINKED ISSUE #234: Change Actor Name Notary to Attester
The naming of the actors got changed again with the [latest spec](https://notes.ethereum.org/SCIg8AH5SA-O4C1G1LYZHQ?view)
While proposer stays the same. The old **notary** whose role is to sign off on block is now called an **attester**. The new notary's role is to sign off on cross link between shard chain and beacon chain. A cross link is a set of signatures that attest to a block in a shard chain. It's important for us to go through our current code base and change the actor's name from notary to attester accordingly.

### PR DESCRIPTION
**Pull request by khelmy**
In response to the name change in the latest spec, this commit changes all references to Notary to Attester, accounting for capitalization, pluralization, gerunds, and the present tense. Resolves #234.

### CODE REVIEW

**Comment by khelmy** [comment]
Fails because it's missing "github.com/prysmaticlabs/geth-sharding/sharding/attester", which is the new name under this scheme for "github.com/prysmaticlabs/geth-sharding/sharding/notary"

**Comment by terenc3t** [comment]
It failed due to different import name. Bazel is expecting notary but we have attester. Did you run `bazel run //:gazelle` to update bazel's BUILD files?

```
-    importpath = "github.com/prysmaticlabs/geth-sharding/sharding/notary",
+    importpath = "github.com/prysmaticlabs/geth-sharding/sharding/attester",
```

**Comment by khelmy** [comment]
Forgot to do that the first time, thanks!

**Comment by prestonvanloon** [comment]
@khelmy Let us know if we can help you get this merged in quickly. There are likely going to be many merge conflicts growing quickly.

**Comment by khelmy** [comment]
All conflicts should be resolved, resolved locally with preference to master branch

**Comment by prestonvanloon** [comment]
@khelmy Github is showing that you still have conflicts. Could you make sure you've pulled down the latest master?

**Comment by rauljordan** [comment]
@khelmy any update on this?

**Comment by khelmy** [comment]
Sorry, been swamped. Fixing conflicts tonight.

**Pull request closed without merging**
