### PR TITLE
Benchmarking Serializer

### PR DESCRIPTION
**Pull request by prestonvanloon**
Initial results:

```
goos: linux
goarch: amd64
pkg: github.com/ethereum/go-ethereum/sharding
BenchmarkSerialization10-4                 20000             84624 ns/op           97347 B/op        565 allocs/op
BenchmarkSerialization100-4                 2000            820836 ns/op          994422 B/op       5528 allocs/op
BenchmarkSerialization1000-4                 200           8076776 ns/op        10630373 B/op      55047 allocs/op
BenchmarkSerialization10000-4                  5         242064047 ns/op        244503252 B/op    350102 allocs/op
PASS
ok      github.com/ethereum/go-ethereum/sharding        9.118s
```

Here's a comparison against other protocols:

Protocol Buffers Marshal: *819 ns/op*
Protocol Buffers Unmarshal: *1163 ns/op*
JSON Marshal: *3316 ns/op*
JSON Unmarshal: *7196 ns/op*
XML Marshal: *9248 ns/op*
XML Unmarshal: *30485 ns/op*
[source](https://medium.com/@shijuvar/benchmarking-protocol-buffers-json-and-xml-in-go-57fa89b8525)

Building off of #136

I'm wondering how much of this is RLP and how much of it is our encoding... To be answered in #139  

We should be at least better than XML so I hope to find some improvements :)

### CODE REVIEW

**Comment by prestonvanloon** [comment]
After some discussion in gitter. Let's leave this as an issue for other contributors to solve or for us to visit again in later phases of the project.

**Comment by nisdas** [comment]
Yeap agreed this would be a good first issue for someone else to start with. I am pretty sure the slow performance comes from RLP which makes heavy use of the reflect package , ideally we would need tests to prove it

**Comment by jamesray1** [comment]
> I am pretty sure the slow performance comes from RLP

Wait isn't this meant to be a replacement for RLP?

**Comment by nisdas** [comment]
> Wait isn't this meant to be a replacement for RLP?

Yeah it is but for our serialization of transactions there are two stages. Once was to convert the transaction type to a byte slice. And the other stage was to perform the actual encoding on the byte slice. We had to use RLP to convert the transactions into a byte slice,  we used RLP for its type conversion library. 

Ideally in the future we will not be using it once we have a separate type conversion library

**Comment by terenc3t** [comment]
Sorry late to the party. It's great to add benchmark related tests in. Thanks @prestonvanloon !

**Pull request merged**
